var dir_5c982d53a68cdbcd421152b4020263a9 =
[
    [ "adc_driver.c", "adc__driver_8c.html", "adc__driver_8c" ],
    [ "adc_driver.h", "adc__driver_8h_source.html", null ],
    [ "button_driver.c", "button__driver_8c_source.html", null ],
    [ "button_driver.h", "button__driver_8h_source.html", null ],
    [ "can_driver.c", "can__driver_8c_source.html", null ],
    [ "can_driver.h", "can__driver_8h_source.html", null ],
    [ "data_ILI9341.c", "data___i_l_i9341_8c_source.html", null ],
    [ "data_ILI9341.h", "data___i_l_i9341_8h_source.html", null ],
    [ "data_logging.c", "data__logging_8c_source.html", null ],
    [ "data_logging.h", "data__logging_8h_source.html", null ],
    [ "defaultfont.h", "defaultfont_8h_source.html", null ],
    [ "font.h", "font_8h_source.html", null ],
    [ "font8x8_basic.h", "font8x8__basic_8h_source.html", null ],
    [ "http_webserver.c", "http__webserver_8c_source.html", null ],
    [ "http_webserver.h", "http__webserver_8h_source.html", null ],
    [ "i2c_driver.c", "i2c__driver_8c_source.html", null ],
    [ "i2c_driver.h", "i2c__driver_8h_source.html", null ],
    [ "main.c", "main_8c_source.html", null ],
    [ "main.h", "main_8h.html", "main_8h" ],
    [ "pwm_driver.c", "pwm__driver_8c_source.html", null ],
    [ "pwm_driver.h", "pwm__driver_8h_source.html", null ],
    [ "spi_driver.c", "spi__driver_8c_source.html", null ],
    [ "spi_driver.h", "spi__driver_8h_source.html", null ],
    [ "spi_lcd_ILI9341.c", "spi__lcd___i_l_i9341_8c_source.html", null ],
    [ "spi_lcd_ILI9341.h", "spi__lcd___i_l_i9341_8h_source.html", null ],
    [ "wifi_driver.c", "wifi__driver_8c_source.html", null ],
    [ "wifi_driver.h", "wifi__driver_8h_source.html", null ]
];